//
// Created by Moritz Winger on 12.05.21.
//

#ifndef AST_OPTIMIZER_INCLUDE_AST_OPT_VISITOR_RUNTIME_DUMMYCIPHERTEXTFACTORY_H_
#define AST_OPTIMIZER_INCLUDE_AST_OPT_VISITOR_RUNTIME_DUMMYCIPHERTEXTFACTORY_H_

#endif //AST_OPTIMIZER_INCLUDE_AST_OPT_VISITOR_RUNTIME_DUMMYCIPHERTEXTFACTORY_H_
