//RUN:  abc-translate -mlir-to-cpp < %s | FileCheck %s
module  {
  func private @encryptedBoxBlur(%arg0: !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext"> {
    %0 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -9 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %1 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -1 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %2 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -57 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %3 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -8 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %4 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -56 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %5 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -7 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %6 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -55 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %7 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, -63 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %8 = emitc.call "evaluator.add_many"(%0, %1, %2, %3, %arg0, %4, %5, %6, %7) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %9 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 1 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %10 = emitc.call "evaluator.add_many"(%0, %1, %2, %3, %arg0, %4, %5, %6, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %11 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 7 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %12 = emitc.call "evaluator.add_many"(%0, %1, %11, %3, %arg0, %4, %5, %6, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %13 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 8 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %14 = emitc.call "evaluator.add_many"(%0, %1, %11, %3, %arg0, %13, %5, %6, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %15 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 9 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %16 = emitc.call "evaluator.add_many"(%0, %1, %11, %3, %arg0, %13, %5, %15, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %17 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 55 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %18 = emitc.call "evaluator.add_many"(%17, %1, %11, %3, %arg0, %13, %5, %15, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %19 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 56 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %20 = emitc.call "evaluator.add_many"(%17, %1, %11, %19, %arg0, %13, %5, %15, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %21 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 57 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %22 = emitc.call "evaluator.add_many"(%17, %1, %11, %19, %arg0, %13, %21, %15, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %23 = emitc.call "evaluator.rotate"(%arg0) {args = [0 : index, 63 : si32]} : (!emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %24 = emitc.call "evaluator.add_many"(%17, %23, %11, %19, %arg0, %13, %21, %15, %9) : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    %25 = emitc.call "evaluator.combine"(%8, %10, %12, %14, %16, %18, %20, %22, %24, %arg0) {args = [0 : index, #emitc.opaque<"{0}">, 1 : index, #emitc.opaque<"{1, 2, 3, 4, 5, 6}">, 2 : index, #emitc.opaque<"{7}">, 3 : index, #emitc.opaque<"{8}">, 4 : index, #emitc.opaque<"{9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54}">, 5 : index, #emitc.opaque<"{55}">, 6 : index, #emitc.opaque<"{56}">, 7 : index, #emitc.opaque<"{57, 58, 59, 60, 61, 62}">, 8 : index, #emitc.opaque<"{63}">, 9 : index, #emitc.opaque<"{}">]} : (!emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">, !emitc.opaque<"seal::Ciphertext">) -> !emitc.opaque<"seal::Ciphertext">
    return %25 : !emitc.opaque<"seal::Ciphertext">
  }
}

// see boxblur_8_cpp.cpp for expected output