// RUN: abc-opt -unroll-loops --canonicalize --cse < %s | FileCheck %s
module  {
  func private @encryptedBoxBlur(%arg0: tensor<64x!fhe.secret<f64>>) -> tensor<64x!fhe.secret<f64>> {
    %c64 = arith.constant 64 : index
    %c8 = arith.constant 8 : index
    %0:4 = affine.for %arg1 = 0 to 8 iter_args(%arg2 = %c8, %arg3 = %c64, %arg4 = %arg0, %arg5 = %arg0) -> (index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>) {
      %1:5 = affine.for %arg6 = 0 to 8 iter_args(%arg7 = %arg2, %arg8 = %arg3, %arg9 = %arg1, %arg10 = %arg4, %arg11 = %arg5) -> (index, index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>) {
        %c0_sf64 = fhe.constant 0.000000e+00 : f64
        %2:7 = affine.for %arg12 = -1 to 2 iter_args(%arg13 = %arg7, %arg14 = %arg8, %arg15 = %arg6, %arg16 = %arg9, %arg17 = %arg10, %arg18 = %arg11, %arg19 = %c0_sf64) -> (index, index, index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>, !fhe.secret<f64>) {
          %6:8 = affine.for %arg20 = -1 to 2 iter_args(%arg21 = %arg13, %arg22 = %arg14, %arg23 = %arg15, %arg24 = %arg12, %arg25 = %arg16, %arg26 = %arg17, %arg27 = %arg18, %arg28 = %arg19) -> (index, index, index, index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>, !fhe.secret<f64>) {
            %7 = arith.addi %arg25, %arg20 : index
            %8 = arith.muli %7, %arg21 : index
            %9 = arith.addi %arg23, %arg24 : index
            %10 = arith.addi %8, %9 : index
            %11 = arith.remui %10, %arg22 : index
            %12 = tensor.extract %arg27[%11] : tensor<64x!fhe.secret<f64>>
            %13 = fhe.add(%arg28, %12) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
            affine.yield %arg21, %arg22, %arg23, %arg24, %arg25, %arg26, %arg27, %13 : index, index, index, index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>, !fhe.secret<f64>
          }
          affine.yield %6#0, %6#1, %6#2, %6#4, %6#5, %6#6, %6#7 : index, index, index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>, !fhe.secret<f64>
        }
        %3 = arith.muli %2#0, %2#3 : index
        %4 = arith.addi %3, %2#2 : index
        %5 = tensor.insert %2#6 into %2#4[%4] : tensor<64x!fhe.secret<f64>>
        affine.yield %2#0, %2#1, %2#3, %5, %2#5 : index, index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>
      }
      affine.yield %1#0, %1#1, %1#3, %1#4 : index, index, tensor<64x!fhe.secret<f64>>, tensor<64x!fhe.secret<f64>>
    }
    return %0#2 : tensor<64x!fhe.secret<f64>>
  }
}

// CHECK: module  {
// CHECK:   func private @encryptedBoxBlur(%arg0: tensor<64x!fhe.secret<f64>>) -> tensor<64x!fhe.secret<f64>> {
// CHECK:     %c63 = arith.constant 63 : index
// CHECK:     %c56 = arith.constant 56 : index
// CHECK:     %c8 = arith.constant 8 : index
// CHECK:     %c1 = arith.constant 1 : index
// CHECK:     %c0 = arith.constant 0 : index
// CHECK:     %c48 = arith.constant 48 : index
// CHECK:     %c6 = arith.constant 6 : index
// CHECK:     %c7 = arith.constant 7 : index
// CHECK:     %c55 = arith.constant 55 : index
// CHECK:     %c62 = arith.constant 62 : index
// CHECK:     %c54 = arith.constant 54 : index
// CHECK:     %c5 = arith.constant 5 : index
// CHECK:     %c61 = arith.constant 61 : index
// CHECK:     %c53 = arith.constant 53 : index
// CHECK:     %c4 = arith.constant 4 : index
// CHECK:     %c60 = arith.constant 60 : index
// CHECK:     %c52 = arith.constant 52 : index
// CHECK:     %c3 = arith.constant 3 : index
// CHECK:     %c59 = arith.constant 59 : index
// CHECK:     %c51 = arith.constant 51 : index
// CHECK:     %c2 = arith.constant 2 : index
// CHECK:     %c58 = arith.constant 58 : index
// CHECK:     %c50 = arith.constant 50 : index
// CHECK:     %c57 = arith.constant 57 : index
// CHECK:     %c49 = arith.constant 49 : index
// CHECK:     %c47 = arith.constant 47 : index
// CHECK:     %c40 = arith.constant 40 : index
// CHECK:     %c46 = arith.constant 46 : index
// CHECK:     %c45 = arith.constant 45 : index
// CHECK:     %c44 = arith.constant 44 : index
// CHECK:     %c43 = arith.constant 43 : index
// CHECK:     %c42 = arith.constant 42 : index
// CHECK:     %c41 = arith.constant 41 : index
// CHECK:     %c39 = arith.constant 39 : index
// CHECK:     %c32 = arith.constant 32 : index
// CHECK:     %c38 = arith.constant 38 : index
// CHECK:     %c37 = arith.constant 37 : index
// CHECK:     %c36 = arith.constant 36 : index
// CHECK:     %c35 = arith.constant 35 : index
// CHECK:     %c34 = arith.constant 34 : index
// CHECK:     %c33 = arith.constant 33 : index
// CHECK:     %c31 = arith.constant 31 : index
// CHECK:     %c24 = arith.constant 24 : index
// CHECK:     %c30 = arith.constant 30 : index
// CHECK:     %c29 = arith.constant 29 : index
// CHECK:     %c28 = arith.constant 28 : index
// CHECK:     %c27 = arith.constant 27 : index
// CHECK:     %c26 = arith.constant 26 : index
// CHECK:     %c25 = arith.constant 25 : index
// CHECK:     %c23 = arith.constant 23 : index
// CHECK:     %c16 = arith.constant 16 : index
// CHECK:     %c22 = arith.constant 22 : index
// CHECK:     %c21 = arith.constant 21 : index
// CHECK:     %c20 = arith.constant 20 : index
// CHECK:     %c19 = arith.constant 19 : index
// CHECK:     %c18 = arith.constant 18 : index
// CHECK:     %c17 = arith.constant 17 : index
// CHECK:     %c15 = arith.constant 15 : index
// CHECK:     %c14 = arith.constant 14 : index
// CHECK:     %c13 = arith.constant 13 : index
// CHECK:     %c12 = arith.constant 12 : index
// CHECK:     %c11 = arith.constant 11 : index
// CHECK:     %c10 = arith.constant 10 : index
// CHECK:     %c9 = arith.constant 9 : index
// CHECK:     %0 = tensor.extract %arg0[%c55] : tensor<64x!fhe.secret<f64>>
// CHECK:     %1 = tensor.extract %arg0[%c63] : tensor<64x!fhe.secret<f64>>
// CHECK:     %2 = fhe.add(%0, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %3 = tensor.extract %arg0[%c7] : tensor<64x!fhe.secret<f64>>
// CHECK:     %4 = fhe.add(%2, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %5 = tensor.extract %arg0[%c56] : tensor<64x!fhe.secret<f64>>
// CHECK:     %6 = fhe.add(%4, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %7 = tensor.extract %arg0[%c0] : tensor<64x!fhe.secret<f64>>
// CHECK:     %8 = fhe.add(%6, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %9 = tensor.extract %arg0[%c8] : tensor<64x!fhe.secret<f64>>
// CHECK:     %10 = fhe.add(%8, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %11 = tensor.extract %arg0[%c57] : tensor<64x!fhe.secret<f64>>
// CHECK:     %12 = fhe.add(%10, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %13 = tensor.extract %arg0[%c1] : tensor<64x!fhe.secret<f64>>
// CHECK:     %14 = fhe.add(%12, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %15 = tensor.extract %arg0[%c9] : tensor<64x!fhe.secret<f64>>
// CHECK:     %16 = fhe.add(%14, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %17 = tensor.insert %16 into %arg0[%c0] : tensor<64x!fhe.secret<f64>>
// CHECK:     %18 = fhe.add(%5, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %19 = fhe.add(%18, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %20 = fhe.add(%19, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %21 = fhe.add(%20, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %22 = fhe.add(%21, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %23 = tensor.extract %arg0[%c58] : tensor<64x!fhe.secret<f64>>
// CHECK:     %24 = fhe.add(%22, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %25 = tensor.extract %arg0[%c2] : tensor<64x!fhe.secret<f64>>
// CHECK:     %26 = fhe.add(%24, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %27 = tensor.extract %arg0[%c10] : tensor<64x!fhe.secret<f64>>
// CHECK:     %28 = fhe.add(%26, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %29 = tensor.insert %28 into %17[%c1] : tensor<64x!fhe.secret<f64>>
// CHECK:     %30 = fhe.add(%11, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %31 = fhe.add(%30, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %32 = fhe.add(%31, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %33 = fhe.add(%32, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %34 = fhe.add(%33, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %35 = tensor.extract %arg0[%c59] : tensor<64x!fhe.secret<f64>>
// CHECK:     %36 = fhe.add(%34, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %37 = tensor.extract %arg0[%c3] : tensor<64x!fhe.secret<f64>>
// CHECK:     %38 = fhe.add(%36, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %39 = tensor.extract %arg0[%c11] : tensor<64x!fhe.secret<f64>>
// CHECK:     %40 = fhe.add(%38, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %41 = tensor.insert %40 into %29[%c2] : tensor<64x!fhe.secret<f64>>
// CHECK:     %42 = fhe.add(%23, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %43 = fhe.add(%42, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %44 = fhe.add(%43, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %45 = fhe.add(%44, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %46 = fhe.add(%45, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %47 = tensor.extract %arg0[%c60] : tensor<64x!fhe.secret<f64>>
// CHECK:     %48 = fhe.add(%46, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %49 = tensor.extract %arg0[%c4] : tensor<64x!fhe.secret<f64>>
// CHECK:     %50 = fhe.add(%48, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %51 = tensor.extract %arg0[%c12] : tensor<64x!fhe.secret<f64>>
// CHECK:     %52 = fhe.add(%50, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %53 = tensor.insert %52 into %41[%c3] : tensor<64x!fhe.secret<f64>>
// CHECK:     %54 = fhe.add(%35, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %55 = fhe.add(%54, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %56 = fhe.add(%55, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %57 = fhe.add(%56, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %58 = fhe.add(%57, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %59 = tensor.extract %arg0[%c61] : tensor<64x!fhe.secret<f64>>
// CHECK:     %60 = fhe.add(%58, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %61 = tensor.extract %arg0[%c5] : tensor<64x!fhe.secret<f64>>
// CHECK:     %62 = fhe.add(%60, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %63 = tensor.extract %arg0[%c13] : tensor<64x!fhe.secret<f64>>
// CHECK:     %64 = fhe.add(%62, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %65 = tensor.insert %64 into %53[%c4] : tensor<64x!fhe.secret<f64>>
// CHECK:     %66 = fhe.add(%47, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %67 = fhe.add(%66, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %68 = fhe.add(%67, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %69 = fhe.add(%68, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %70 = fhe.add(%69, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %71 = tensor.extract %arg0[%c62] : tensor<64x!fhe.secret<f64>>
// CHECK:     %72 = fhe.add(%70, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %73 = tensor.extract %arg0[%c6] : tensor<64x!fhe.secret<f64>>
// CHECK:     %74 = fhe.add(%72, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %75 = tensor.extract %arg0[%c14] : tensor<64x!fhe.secret<f64>>
// CHECK:     %76 = fhe.add(%74, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %77 = tensor.insert %76 into %65[%c5] : tensor<64x!fhe.secret<f64>>
// CHECK:     %78 = fhe.add(%59, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %79 = fhe.add(%78, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %80 = fhe.add(%79, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %81 = fhe.add(%80, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %82 = fhe.add(%81, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %83 = fhe.add(%82, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %84 = fhe.add(%83, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %85 = tensor.extract %arg0[%c15] : tensor<64x!fhe.secret<f64>>
// CHECK:     %86 = fhe.add(%84, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %87 = tensor.insert %86 into %77[%c6] : tensor<64x!fhe.secret<f64>>
// CHECK:     %88 = fhe.add(%71, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %89 = fhe.add(%88, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %90 = fhe.add(%89, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %91 = fhe.add(%90, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %92 = fhe.add(%91, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %93 = fhe.add(%92, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %94 = fhe.add(%93, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %95 = tensor.extract %arg0[%c16] : tensor<64x!fhe.secret<f64>>
// CHECK:     %96 = fhe.add(%94, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %97 = tensor.insert %96 into %87[%c7] : tensor<64x!fhe.secret<f64>>
// CHECK:     %98 = fhe.add(%1, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %99 = fhe.add(%98, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %100 = fhe.add(%99, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %101 = fhe.add(%100, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %102 = fhe.add(%101, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %103 = fhe.add(%102, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %104 = fhe.add(%103, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %105 = tensor.extract %arg0[%c17] : tensor<64x!fhe.secret<f64>>
// CHECK:     %106 = fhe.add(%104, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %107 = tensor.insert %106 into %97[%c8] : tensor<64x!fhe.secret<f64>>
// CHECK:     %108 = fhe.add(%7, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %109 = fhe.add(%108, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %110 = fhe.add(%109, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %111 = fhe.add(%110, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %112 = fhe.add(%111, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %113 = fhe.add(%112, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %114 = fhe.add(%113, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %115 = tensor.extract %arg0[%c18] : tensor<64x!fhe.secret<f64>>
// CHECK:     %116 = fhe.add(%114, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %117 = tensor.insert %116 into %107[%c9] : tensor<64x!fhe.secret<f64>>
// CHECK:     %118 = fhe.add(%13, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %119 = fhe.add(%118, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %120 = fhe.add(%119, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %121 = fhe.add(%120, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %122 = fhe.add(%121, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %123 = fhe.add(%122, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %124 = fhe.add(%123, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %125 = tensor.extract %arg0[%c19] : tensor<64x!fhe.secret<f64>>
// CHECK:     %126 = fhe.add(%124, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %127 = tensor.insert %126 into %117[%c10] : tensor<64x!fhe.secret<f64>>
// CHECK:     %128 = fhe.add(%25, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %129 = fhe.add(%128, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %130 = fhe.add(%129, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %131 = fhe.add(%130, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %132 = fhe.add(%131, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %133 = fhe.add(%132, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %134 = fhe.add(%133, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %135 = tensor.extract %arg0[%c20] : tensor<64x!fhe.secret<f64>>
// CHECK:     %136 = fhe.add(%134, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %137 = tensor.insert %136 into %127[%c11] : tensor<64x!fhe.secret<f64>>
// CHECK:     %138 = fhe.add(%37, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %139 = fhe.add(%138, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %140 = fhe.add(%139, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %141 = fhe.add(%140, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %142 = fhe.add(%141, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %143 = fhe.add(%142, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %144 = fhe.add(%143, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %145 = tensor.extract %arg0[%c21] : tensor<64x!fhe.secret<f64>>
// CHECK:     %146 = fhe.add(%144, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %147 = tensor.insert %146 into %137[%c12] : tensor<64x!fhe.secret<f64>>
// CHECK:     %148 = fhe.add(%49, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %149 = fhe.add(%148, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %150 = fhe.add(%149, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %151 = fhe.add(%150, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %152 = fhe.add(%151, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %153 = fhe.add(%152, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %154 = fhe.add(%153, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %155 = tensor.extract %arg0[%c22] : tensor<64x!fhe.secret<f64>>
// CHECK:     %156 = fhe.add(%154, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %157 = tensor.insert %156 into %147[%c13] : tensor<64x!fhe.secret<f64>>
// CHECK:     %158 = fhe.add(%61, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %159 = fhe.add(%158, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %160 = fhe.add(%159, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %161 = fhe.add(%160, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %162 = fhe.add(%161, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %163 = fhe.add(%162, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %164 = fhe.add(%163, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %165 = tensor.extract %arg0[%c23] : tensor<64x!fhe.secret<f64>>
// CHECK:     %166 = fhe.add(%164, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %167 = tensor.insert %166 into %157[%c14] : tensor<64x!fhe.secret<f64>>
// CHECK:     %168 = fhe.add(%73, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %169 = fhe.add(%168, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %170 = fhe.add(%169, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %171 = fhe.add(%170, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %172 = fhe.add(%171, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %173 = fhe.add(%172, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %174 = fhe.add(%173, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %175 = tensor.extract %arg0[%c24] : tensor<64x!fhe.secret<f64>>
// CHECK:     %176 = fhe.add(%174, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %177 = tensor.insert %176 into %167[%c15] : tensor<64x!fhe.secret<f64>>
// CHECK:     %178 = fhe.add(%3, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %179 = fhe.add(%178, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %180 = fhe.add(%179, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %181 = fhe.add(%180, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %182 = fhe.add(%181, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %183 = fhe.add(%182, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %184 = fhe.add(%183, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %185 = tensor.extract %arg0[%c25] : tensor<64x!fhe.secret<f64>>
// CHECK:     %186 = fhe.add(%184, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %187 = tensor.insert %186 into %177[%c16] : tensor<64x!fhe.secret<f64>>
// CHECK:     %188 = fhe.add(%9, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %189 = fhe.add(%188, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %190 = fhe.add(%189, %15) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %191 = fhe.add(%190, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %192 = fhe.add(%191, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %193 = fhe.add(%192, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %194 = fhe.add(%193, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %195 = tensor.extract %arg0[%c26] : tensor<64x!fhe.secret<f64>>
// CHECK:     %196 = fhe.add(%194, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %197 = tensor.insert %196 into %187[%c17] : tensor<64x!fhe.secret<f64>>
// CHECK:     %198 = fhe.add(%15, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %199 = fhe.add(%198, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %200 = fhe.add(%199, %27) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %201 = fhe.add(%200, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %202 = fhe.add(%201, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %203 = fhe.add(%202, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %204 = fhe.add(%203, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %205 = tensor.extract %arg0[%c27] : tensor<64x!fhe.secret<f64>>
// CHECK:     %206 = fhe.add(%204, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %207 = tensor.insert %206 into %197[%c18] : tensor<64x!fhe.secret<f64>>
// CHECK:     %208 = fhe.add(%27, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %209 = fhe.add(%208, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %210 = fhe.add(%209, %39) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %211 = fhe.add(%210, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %212 = fhe.add(%211, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %213 = fhe.add(%212, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %214 = fhe.add(%213, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %215 = tensor.extract %arg0[%c28] : tensor<64x!fhe.secret<f64>>
// CHECK:     %216 = fhe.add(%214, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %217 = tensor.insert %216 into %207[%c19] : tensor<64x!fhe.secret<f64>>
// CHECK:     %218 = fhe.add(%39, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %219 = fhe.add(%218, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %220 = fhe.add(%219, %51) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %221 = fhe.add(%220, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %222 = fhe.add(%221, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %223 = fhe.add(%222, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %224 = fhe.add(%223, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %225 = tensor.extract %arg0[%c29] : tensor<64x!fhe.secret<f64>>
// CHECK:     %226 = fhe.add(%224, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %227 = tensor.insert %226 into %217[%c20] : tensor<64x!fhe.secret<f64>>
// CHECK:     %228 = fhe.add(%51, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %229 = fhe.add(%228, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %230 = fhe.add(%229, %63) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %231 = fhe.add(%230, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %232 = fhe.add(%231, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %233 = fhe.add(%232, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %234 = fhe.add(%233, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %235 = tensor.extract %arg0[%c30] : tensor<64x!fhe.secret<f64>>
// CHECK:     %236 = fhe.add(%234, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %237 = tensor.insert %236 into %227[%c21] : tensor<64x!fhe.secret<f64>>
// CHECK:     %238 = fhe.add(%63, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %239 = fhe.add(%238, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %240 = fhe.add(%239, %75) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %241 = fhe.add(%240, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %242 = fhe.add(%241, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %243 = fhe.add(%242, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %244 = fhe.add(%243, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %245 = tensor.extract %arg0[%c31] : tensor<64x!fhe.secret<f64>>
// CHECK:     %246 = fhe.add(%244, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %247 = tensor.insert %246 into %237[%c22] : tensor<64x!fhe.secret<f64>>
// CHECK:     %248 = fhe.add(%75, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %249 = fhe.add(%248, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %250 = fhe.add(%249, %85) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %251 = fhe.add(%250, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %252 = fhe.add(%251, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %253 = fhe.add(%252, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %254 = fhe.add(%253, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %255 = tensor.extract %arg0[%c32] : tensor<64x!fhe.secret<f64>>
// CHECK:     %256 = fhe.add(%254, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %257 = tensor.insert %256 into %247[%c23] : tensor<64x!fhe.secret<f64>>
// CHECK:     %258 = fhe.add(%85, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %259 = fhe.add(%258, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %260 = fhe.add(%259, %95) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %261 = fhe.add(%260, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %262 = fhe.add(%261, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %263 = fhe.add(%262, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %264 = fhe.add(%263, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %265 = tensor.extract %arg0[%c33] : tensor<64x!fhe.secret<f64>>
// CHECK:     %266 = fhe.add(%264, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %267 = tensor.insert %266 into %257[%c24] : tensor<64x!fhe.secret<f64>>
// CHECK:     %268 = fhe.add(%95, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %269 = fhe.add(%268, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %270 = fhe.add(%269, %105) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %271 = fhe.add(%270, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %272 = fhe.add(%271, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %273 = fhe.add(%272, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %274 = fhe.add(%273, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %275 = tensor.extract %arg0[%c34] : tensor<64x!fhe.secret<f64>>
// CHECK:     %276 = fhe.add(%274, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %277 = tensor.insert %276 into %267[%c25] : tensor<64x!fhe.secret<f64>>
// CHECK:     %278 = fhe.add(%105, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %279 = fhe.add(%278, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %280 = fhe.add(%279, %115) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %281 = fhe.add(%280, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %282 = fhe.add(%281, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %283 = fhe.add(%282, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %284 = fhe.add(%283, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %285 = tensor.extract %arg0[%c35] : tensor<64x!fhe.secret<f64>>
// CHECK:     %286 = fhe.add(%284, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %287 = tensor.insert %286 into %277[%c26] : tensor<64x!fhe.secret<f64>>
// CHECK:     %288 = fhe.add(%115, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %289 = fhe.add(%288, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %290 = fhe.add(%289, %125) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %291 = fhe.add(%290, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %292 = fhe.add(%291, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %293 = fhe.add(%292, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %294 = fhe.add(%293, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %295 = tensor.extract %arg0[%c36] : tensor<64x!fhe.secret<f64>>
// CHECK:     %296 = fhe.add(%294, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %297 = tensor.insert %296 into %287[%c27] : tensor<64x!fhe.secret<f64>>
// CHECK:     %298 = fhe.add(%125, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %299 = fhe.add(%298, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %300 = fhe.add(%299, %135) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %301 = fhe.add(%300, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %302 = fhe.add(%301, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %303 = fhe.add(%302, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %304 = fhe.add(%303, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %305 = tensor.extract %arg0[%c37] : tensor<64x!fhe.secret<f64>>
// CHECK:     %306 = fhe.add(%304, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %307 = tensor.insert %306 into %297[%c28] : tensor<64x!fhe.secret<f64>>
// CHECK:     %308 = fhe.add(%135, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %309 = fhe.add(%308, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %310 = fhe.add(%309, %145) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %311 = fhe.add(%310, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %312 = fhe.add(%311, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %313 = fhe.add(%312, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %314 = fhe.add(%313, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %315 = tensor.extract %arg0[%c38] : tensor<64x!fhe.secret<f64>>
// CHECK:     %316 = fhe.add(%314, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %317 = tensor.insert %316 into %307[%c29] : tensor<64x!fhe.secret<f64>>
// CHECK:     %318 = fhe.add(%145, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %319 = fhe.add(%318, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %320 = fhe.add(%319, %155) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %321 = fhe.add(%320, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %322 = fhe.add(%321, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %323 = fhe.add(%322, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %324 = fhe.add(%323, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %325 = tensor.extract %arg0[%c39] : tensor<64x!fhe.secret<f64>>
// CHECK:     %326 = fhe.add(%324, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %327 = tensor.insert %326 into %317[%c30] : tensor<64x!fhe.secret<f64>>
// CHECK:     %328 = fhe.add(%155, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %329 = fhe.add(%328, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %330 = fhe.add(%329, %165) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %331 = fhe.add(%330, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %332 = fhe.add(%331, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %333 = fhe.add(%332, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %334 = fhe.add(%333, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %335 = tensor.extract %arg0[%c40] : tensor<64x!fhe.secret<f64>>
// CHECK:     %336 = fhe.add(%334, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %337 = tensor.insert %336 into %327[%c31] : tensor<64x!fhe.secret<f64>>
// CHECK:     %338 = fhe.add(%165, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %339 = fhe.add(%338, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %340 = fhe.add(%339, %175) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %341 = fhe.add(%340, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %342 = fhe.add(%341, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %343 = fhe.add(%342, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %344 = fhe.add(%343, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %345 = tensor.extract %arg0[%c41] : tensor<64x!fhe.secret<f64>>
// CHECK:     %346 = fhe.add(%344, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %347 = tensor.insert %346 into %337[%c32] : tensor<64x!fhe.secret<f64>>
// CHECK:     %348 = fhe.add(%175, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %349 = fhe.add(%348, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %350 = fhe.add(%349, %185) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %351 = fhe.add(%350, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %352 = fhe.add(%351, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %353 = fhe.add(%352, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %354 = fhe.add(%353, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %355 = tensor.extract %arg0[%c42] : tensor<64x!fhe.secret<f64>>
// CHECK:     %356 = fhe.add(%354, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %357 = tensor.insert %356 into %347[%c33] : tensor<64x!fhe.secret<f64>>
// CHECK:     %358 = fhe.add(%185, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %359 = fhe.add(%358, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %360 = fhe.add(%359, %195) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %361 = fhe.add(%360, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %362 = fhe.add(%361, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %363 = fhe.add(%362, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %364 = fhe.add(%363, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %365 = tensor.extract %arg0[%c43] : tensor<64x!fhe.secret<f64>>
// CHECK:     %366 = fhe.add(%364, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %367 = tensor.insert %366 into %357[%c34] : tensor<64x!fhe.secret<f64>>
// CHECK:     %368 = fhe.add(%195, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %369 = fhe.add(%368, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %370 = fhe.add(%369, %205) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %371 = fhe.add(%370, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %372 = fhe.add(%371, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %373 = fhe.add(%372, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %374 = fhe.add(%373, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %375 = tensor.extract %arg0[%c44] : tensor<64x!fhe.secret<f64>>
// CHECK:     %376 = fhe.add(%374, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %377 = tensor.insert %376 into %367[%c35] : tensor<64x!fhe.secret<f64>>
// CHECK:     %378 = fhe.add(%205, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %379 = fhe.add(%378, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %380 = fhe.add(%379, %215) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %381 = fhe.add(%380, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %382 = fhe.add(%381, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %383 = fhe.add(%382, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %384 = fhe.add(%383, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %385 = tensor.extract %arg0[%c45] : tensor<64x!fhe.secret<f64>>
// CHECK:     %386 = fhe.add(%384, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %387 = tensor.insert %386 into %377[%c36] : tensor<64x!fhe.secret<f64>>
// CHECK:     %388 = fhe.add(%215, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %389 = fhe.add(%388, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %390 = fhe.add(%389, %225) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %391 = fhe.add(%390, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %392 = fhe.add(%391, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %393 = fhe.add(%392, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %394 = fhe.add(%393, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %395 = tensor.extract %arg0[%c46] : tensor<64x!fhe.secret<f64>>
// CHECK:     %396 = fhe.add(%394, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %397 = tensor.insert %396 into %387[%c37] : tensor<64x!fhe.secret<f64>>
// CHECK:     %398 = fhe.add(%225, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %399 = fhe.add(%398, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %400 = fhe.add(%399, %235) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %401 = fhe.add(%400, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %402 = fhe.add(%401, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %403 = fhe.add(%402, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %404 = fhe.add(%403, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %405 = tensor.extract %arg0[%c47] : tensor<64x!fhe.secret<f64>>
// CHECK:     %406 = fhe.add(%404, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %407 = tensor.insert %406 into %397[%c38] : tensor<64x!fhe.secret<f64>>
// CHECK:     %408 = fhe.add(%235, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %409 = fhe.add(%408, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %410 = fhe.add(%409, %245) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %411 = fhe.add(%410, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %412 = fhe.add(%411, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %413 = fhe.add(%412, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %414 = fhe.add(%413, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %415 = tensor.extract %arg0[%c48] : tensor<64x!fhe.secret<f64>>
// CHECK:     %416 = fhe.add(%414, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %417 = tensor.insert %416 into %407[%c39] : tensor<64x!fhe.secret<f64>>
// CHECK:     %418 = fhe.add(%245, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %419 = fhe.add(%418, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %420 = fhe.add(%419, %255) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %421 = fhe.add(%420, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %422 = fhe.add(%421, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %423 = fhe.add(%422, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %424 = fhe.add(%423, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %425 = tensor.extract %arg0[%c49] : tensor<64x!fhe.secret<f64>>
// CHECK:     %426 = fhe.add(%424, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %427 = tensor.insert %426 into %417[%c40] : tensor<64x!fhe.secret<f64>>
// CHECK:     %428 = fhe.add(%255, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %429 = fhe.add(%428, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %430 = fhe.add(%429, %265) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %431 = fhe.add(%430, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %432 = fhe.add(%431, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %433 = fhe.add(%432, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %434 = fhe.add(%433, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %435 = tensor.extract %arg0[%c50] : tensor<64x!fhe.secret<f64>>
// CHECK:     %436 = fhe.add(%434, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %437 = tensor.insert %436 into %427[%c41] : tensor<64x!fhe.secret<f64>>
// CHECK:     %438 = fhe.add(%265, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %439 = fhe.add(%438, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %440 = fhe.add(%439, %275) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %441 = fhe.add(%440, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %442 = fhe.add(%441, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %443 = fhe.add(%442, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %444 = fhe.add(%443, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %445 = tensor.extract %arg0[%c51] : tensor<64x!fhe.secret<f64>>
// CHECK:     %446 = fhe.add(%444, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %447 = tensor.insert %446 into %437[%c42] : tensor<64x!fhe.secret<f64>>
// CHECK:     %448 = fhe.add(%275, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %449 = fhe.add(%448, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %450 = fhe.add(%449, %285) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %451 = fhe.add(%450, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %452 = fhe.add(%451, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %453 = fhe.add(%452, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %454 = fhe.add(%453, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %455 = tensor.extract %arg0[%c52] : tensor<64x!fhe.secret<f64>>
// CHECK:     %456 = fhe.add(%454, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %457 = tensor.insert %456 into %447[%c43] : tensor<64x!fhe.secret<f64>>
// CHECK:     %458 = fhe.add(%285, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %459 = fhe.add(%458, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %460 = fhe.add(%459, %295) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %461 = fhe.add(%460, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %462 = fhe.add(%461, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %463 = fhe.add(%462, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %464 = fhe.add(%463, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %465 = tensor.extract %arg0[%c53] : tensor<64x!fhe.secret<f64>>
// CHECK:     %466 = fhe.add(%464, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %467 = tensor.insert %466 into %457[%c44] : tensor<64x!fhe.secret<f64>>
// CHECK:     %468 = fhe.add(%295, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %469 = fhe.add(%468, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %470 = fhe.add(%469, %305) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %471 = fhe.add(%470, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %472 = fhe.add(%471, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %473 = fhe.add(%472, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %474 = fhe.add(%473, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %475 = tensor.extract %arg0[%c54] : tensor<64x!fhe.secret<f64>>
// CHECK:     %476 = fhe.add(%474, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %477 = tensor.insert %476 into %467[%c45] : tensor<64x!fhe.secret<f64>>
// CHECK:     %478 = fhe.add(%305, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %479 = fhe.add(%478, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %480 = fhe.add(%479, %315) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %481 = fhe.add(%480, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %482 = fhe.add(%481, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %483 = fhe.add(%482, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %484 = fhe.add(%483, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %485 = fhe.add(%484, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %486 = tensor.insert %485 into %477[%c46] : tensor<64x!fhe.secret<f64>>
// CHECK:     %487 = fhe.add(%315, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %488 = fhe.add(%487, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %489 = fhe.add(%488, %325) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %490 = fhe.add(%489, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %491 = fhe.add(%490, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %492 = fhe.add(%491, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %493 = fhe.add(%492, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %494 = fhe.add(%493, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %495 = tensor.insert %494 into %486[%c47] : tensor<64x!fhe.secret<f64>>
// CHECK:     %496 = fhe.add(%325, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %497 = fhe.add(%496, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %498 = fhe.add(%497, %335) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %499 = fhe.add(%498, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %500 = fhe.add(%499, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %501 = fhe.add(%500, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %502 = fhe.add(%501, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %503 = fhe.add(%502, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %504 = tensor.insert %503 into %495[%c48] : tensor<64x!fhe.secret<f64>>
// CHECK:     %505 = fhe.add(%335, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %506 = fhe.add(%505, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %507 = fhe.add(%506, %345) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %508 = fhe.add(%507, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %509 = fhe.add(%508, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %510 = fhe.add(%509, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %511 = fhe.add(%510, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %512 = fhe.add(%511, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %513 = tensor.insert %512 into %504[%c49] : tensor<64x!fhe.secret<f64>>
// CHECK:     %514 = fhe.add(%345, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %515 = fhe.add(%514, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %516 = fhe.add(%515, %355) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %517 = fhe.add(%516, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %518 = fhe.add(%517, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %519 = fhe.add(%518, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %520 = fhe.add(%519, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %521 = fhe.add(%520, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %522 = tensor.insert %521 into %513[%c50] : tensor<64x!fhe.secret<f64>>
// CHECK:     %523 = fhe.add(%355, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %524 = fhe.add(%523, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %525 = fhe.add(%524, %365) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %526 = fhe.add(%525, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %527 = fhe.add(%526, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %528 = fhe.add(%527, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %529 = fhe.add(%528, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %530 = fhe.add(%529, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %531 = tensor.insert %530 into %522[%c51] : tensor<64x!fhe.secret<f64>>
// CHECK:     %532 = fhe.add(%365, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %533 = fhe.add(%532, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %534 = fhe.add(%533, %375) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %535 = fhe.add(%534, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %536 = fhe.add(%535, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %537 = fhe.add(%536, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %538 = fhe.add(%537, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %539 = fhe.add(%538, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %540 = tensor.insert %539 into %531[%c52] : tensor<64x!fhe.secret<f64>>
// CHECK:     %541 = fhe.add(%375, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %542 = fhe.add(%541, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %543 = fhe.add(%542, %385) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %544 = fhe.add(%543, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %545 = fhe.add(%544, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %546 = fhe.add(%545, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %547 = fhe.add(%546, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %548 = fhe.add(%547, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %549 = tensor.insert %548 into %540[%c53] : tensor<64x!fhe.secret<f64>>
// CHECK:     %550 = fhe.add(%385, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %551 = fhe.add(%550, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %552 = fhe.add(%551, %395) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %553 = fhe.add(%552, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %554 = fhe.add(%553, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %555 = fhe.add(%554, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %556 = fhe.add(%555, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %557 = fhe.add(%556, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %558 = tensor.insert %557 into %549[%c54] : tensor<64x!fhe.secret<f64>>
// CHECK:     %559 = fhe.add(%395, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %560 = fhe.add(%559, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %561 = fhe.add(%560, %405) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %562 = fhe.add(%561, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %563 = fhe.add(%562, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %564 = fhe.add(%563, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %565 = fhe.add(%564, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %566 = fhe.add(%565, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %567 = tensor.insert %566 into %558[%c55] : tensor<64x!fhe.secret<f64>>
// CHECK:     %568 = fhe.add(%405, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %569 = fhe.add(%568, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %570 = fhe.add(%569, %415) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %571 = fhe.add(%570, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %572 = fhe.add(%571, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %573 = fhe.add(%572, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %574 = fhe.add(%573, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %575 = fhe.add(%574, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %576 = tensor.insert %575 into %567[%c56] : tensor<64x!fhe.secret<f64>>
// CHECK:     %577 = fhe.add(%415, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %578 = fhe.add(%577, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %579 = fhe.add(%578, %425) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %580 = fhe.add(%579, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %581 = fhe.add(%580, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %582 = fhe.add(%581, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %583 = fhe.add(%582, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %584 = fhe.add(%583, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %585 = tensor.insert %584 into %576[%c57] : tensor<64x!fhe.secret<f64>>
// CHECK:     %586 = fhe.add(%425, %11) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %587 = fhe.add(%586, %13) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %588 = fhe.add(%587, %435) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %589 = fhe.add(%588, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %590 = fhe.add(%589, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %591 = fhe.add(%590, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %592 = fhe.add(%591, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %593 = fhe.add(%592, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %594 = tensor.insert %593 into %585[%c58] : tensor<64x!fhe.secret<f64>>
// CHECK:     %595 = fhe.add(%435, %23) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %596 = fhe.add(%595, %25) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %597 = fhe.add(%596, %445) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %598 = fhe.add(%597, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %599 = fhe.add(%598, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %600 = fhe.add(%599, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %601 = fhe.add(%600, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %602 = fhe.add(%601, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %603 = tensor.insert %602 into %594[%c59] : tensor<64x!fhe.secret<f64>>
// CHECK:     %604 = fhe.add(%445, %35) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %605 = fhe.add(%604, %37) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %606 = fhe.add(%605, %455) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %607 = fhe.add(%606, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %608 = fhe.add(%607, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %609 = fhe.add(%608, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %610 = fhe.add(%609, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %611 = fhe.add(%610, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %612 = tensor.insert %611 into %603[%c60] : tensor<64x!fhe.secret<f64>>
// CHECK:     %613 = fhe.add(%455, %47) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %614 = fhe.add(%613, %49) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %615 = fhe.add(%614, %465) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %616 = fhe.add(%615, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %617 = fhe.add(%616, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %618 = fhe.add(%617, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %619 = fhe.add(%618, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %620 = fhe.add(%619, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %621 = tensor.insert %620 into %612[%c61] : tensor<64x!fhe.secret<f64>>
// CHECK:     %622 = fhe.add(%465, %59) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %623 = fhe.add(%622, %61) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %624 = fhe.add(%623, %475) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %625 = fhe.add(%624, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %626 = fhe.add(%625, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %627 = fhe.add(%626, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %628 = fhe.add(%627, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %629 = fhe.add(%628, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %630 = tensor.insert %629 into %621[%c62] : tensor<64x!fhe.secret<f64>>
// CHECK:     %631 = fhe.add(%475, %71) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %632 = fhe.add(%631, %73) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %633 = fhe.add(%632, %0) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %634 = fhe.add(%633, %1) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %635 = fhe.add(%634, %3) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %636 = fhe.add(%635, %5) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %637 = fhe.add(%636, %7) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %638 = fhe.add(%637, %9) : (!fhe.secret<f64>, !fhe.secret<f64>) -> !fhe.secret<f64>
// CHECK:     %639 = tensor.insert %638 into %630[%c63] : tensor<64x!fhe.secret<f64>>
// CHECK:     return %639 : tensor<64x!fhe.secret<f64>>
// CHECK:   }
// CHECK: }
