//
// Created by Moritz Winger on 05.05.21.
//

#ifndef AST_OPTIMIZER_TEST_VISITOR_RUNTIME_SIMULATORCIPHERTEXTFACTORY_H_
#define AST_OPTIMIZER_TEST_VISITOR_RUNTIME_SIMULATORCIPHERTEXTFACTORY_H_

class SimulatorCiphertextFactory {

};

#endif //AST_OPTIMIZER_TEST_VISITOR_RUNTIME_SIMULATORCIPHERTEXTFACTORY_H_
